## Homework_4

In [1]:
from math import factorial
from math import e
from math import sqrt

In [2]:
def combinations (n, k):
    return int(factorial(n) / (factorial(k) * factorial(n - k)))

1. Случайная непрерывная величина A имеет равномерное распределение на промежутке (200, 800].
Найдите ее среднее значение и дисперсию.

In [3]:
a = 200
b = 800

In [4]:
mean = (a + b) / 2

In [5]:
variance = (b - a)**2 / 12

In [6]:
print("mean_1:", mean)
print("variance_1:", variance)

mean_1: 500.0
variance_1: 30000.0


2.	О случайной непрерывной равномерно распределенной величине B известно, что ее дисперсия равна 0.2.
Можно ли найти правую границу величины B и ее среднее значение зная, что левая граница равна 0.5?
Если да, найдите ее.

In [7]:
variance_B = 0.2

In [8]:
a_B = 0.5

In [9]:
b_B = sqrt(12 * variance_B) + a_B

In [10]:
mean_B = (a_B + b_B) / 2

In [11]:
print("b_B:", b_B)
print("mean_B:", mean_B)

b_B: 2.049193338482967
mean_B: 1.2745966692414834


3.	Непрерывная случайная величина X распределена нормально и задана плотностью распределения
f(x) = (1 / (4 * sqrt(2*pi))) * (exp(-(x+2)**2) / 32).
Найдите:
а). M(X)
б). D(X)
в). std(X) (среднее квадратичное отклонение)

In [12]:
mean_X = -2

In [13]:
variance_X = 4**2

In [14]:
std_X = 4

In [15]:
print("mean_X:", mean_X)
print("variance_X:", variance_X)
print("std_X:", std_X)

mean_X: -2
variance_X: 16
std_X: 4


4.	Рост взрослого населения города X имеет нормальное распределение.
Причем, средний рост равен 174 см, а среднее квадратичное отклонение равно 8 см.
Какова вероятность того, что случайным образом выбранный взрослый человек имеет рост:
а). больше 182 см
б). больше 190 см
в). от 166 см до 190 см
г). от 166 см до 182 см
д). от 158 см до 190 см
е). не выше 150 см или не ниже 190 см
ё). не выше 150 см или не ниже 198 см
ж). ниже 166 см.

In [16]:
mean_height = 174

In [17]:
std_height = 8

In [18]:
# справочно:

In [19]:
std_1plus = mean_height + std_height
std_1plus

182

In [20]:
std_1minus = mean_height - std_height
std_1minus

166

In [21]:
std_2plus = mean_height + 2*std_height
std_2plus

190

In [22]:
std_2minus = mean_height - 2*std_height
std_2minus

158

In [23]:
std_3plus = mean_height + 3*std_height
std_3plus

198

In [24]:
std_3minus = mean_height - 3*std_height
std_3minus

150

а) больше 182 см 

In [25]:
# больше +1 сигмы
variance_5a = 1 - 0.8413
variance_5a 

0.15869999999999995

б) больше 190 см

In [26]:
# больше +2 сигмы
variance_5b = 1 - 0.9772
variance_5b 

0.022800000000000042

в) от 166 см до 190 см

In [27]:
# от -1 до +2 сигмы
variance_5с = 0.9772 - 0.1587
variance_5с 

0.8185

г) от 166 см до 182 см

In [28]:
# от -1 до +1 сигмы
variance_5d = 0.8413 - 0.1587
variance_5d 

0.6826000000000001

д) от 158 см до 190 см

In [29]:
# от -2 до +2 сигмы
variance_5e = 0.9772 - 0.0228
variance_5e

0.9543999999999999

е) не выше 150 см или не ниже 190 см

In [30]:
# до -3  и от +2 сигмы
variance_5f = 0.0013 + variance_5b
variance_5f

0.02410000000000004

ё) не выше 150 см или не ниже 198 см

In [31]:
# до -3  и от +3 сигмы
variance_5g = 0.0013 * 2
variance_5g 

0.0026

ж) ниже 166 см

In [32]:
# до -1 сигмы
variance_5h = 0.1587
variance_5h

0.1587

5.	На сколько сигм (средних квадратичных отклонений) отклоняется рост человека, равный 190 см, от
математического ожидания роста в популяции, в которой M(X) = 178 см и D(X) = 25 кв.см?

In [33]:
std_5 = sqrt(25)

In [34]:
number_std = (190 - 178) / std_5
number_std

2.4